/// Canonical lint report: `.odc/odc-errors.md`. Legacy root `ods-error.md` is cleared on write/clear.
fn lint_error_report_path(root: &Path) -> PathBuf {
    root.join(".odc").join("odc-errors.md")
}

fn legacy_lint_error_report_path(root: &Path) -> PathBuf {
    root.join("ods-error.md")
}

fn write_or_clear_ods_error_report(
    root: &Path,
    diagnostics: &[Diagnostic],
    format: OutputFormat,
) -> Result<(), CliError> {
    let path = lint_error_report_path(root);
    let legacy = legacy_lint_error_report_path(root);
    if diagnostics.is_empty() {
        if path.is_file() {
            let _ = fs::remove_file(&path);
        }
        if legacy.is_file() {
            let _ = fs::remove_file(&legacy);
        }
        return Ok(());
    }
    // Only write the markdown report for human text mode (not pure JSON CI).
    if !matches!(format, OutputFormat::Text) {
        return Ok(());
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).map_err(|err| failure(err.to_string()))?;
    }
    let mut body = String::from(
        "---\nods:\n  profile: note\n  status: draft\n  description: OpenDocify health report — auto-generated by odc lint / odc watch\n---\n\n# OpenDocify errors\n\n",
    );
    const MAX_REPORT_DIAGNOSTICS: usize = 500;
    let total = diagnostics.len();
    let errors = diagnostics
        .iter()
        .filter(|d| matches!(d.severity, Severity::Error))
        .count();
    let warnings = total.saturating_sub(errors);
    body.push_str(&format!(
        "Summary: **{total}** issue(s) ({errors} error(s), {warnings} warning(s)).\n\n"
    ));
    body.push_str(
        "Fix the items below, then re-run `odc lint` (or keep `odc watch` running).\n\n",
    );
    let shown = diagnostics.len().min(MAX_REPORT_DIAGNOSTICS);
    for diagnostic in diagnostics.iter().take(shown) {
        let severity = match diagnostic.severity {
            Severity::Error => "error",
            Severity::Warning => "warning",
        };
        let rel = diagnostic
            .path
            .strip_prefix(root)
            .unwrap_or(&diagnostic.path);
        body.push_str(&format!(
            "- **{severity}** `{}`: {}\n",
            rel.display(),
            diagnostic.message
        ));
    }
    if total > MAX_REPORT_DIAGNOSTICS {
        body.push_str(&format!(
            "\n_…and {} more not listed (cap {MAX_REPORT_DIAGNOSTICS}). Use `odc lint --format json` for full output._\n",
            total - MAX_REPORT_DIAGNOSTICS
        ));
    }
    fs::write(&path, body).map_err(|err| failure(err.to_string()))?;
    // Drop legacy root report so tools do not double-report.
    if legacy.is_file() {
        let _ = fs::remove_file(&legacy);
    }
    eprintln!("wrote {}", path.display());
    Ok(())
}
