fn dispatch_agents_command(args: &[String]) -> Result<ExitCode, CliError> {
    let sub = args.get(2).map(String::as_str).unwrap_or("help");
    match sub {
        "help" | "--help" | "-h" | "" => {
            println!(
                "odc agents <command>\n\n\
                 Agent instruction graph commands.\n\n\
                 Commands:\n\
                   sync [path]   Write/update AGENTS.md (+ optional .claude/.cursor snippets)\n\
                   help          Show this help\n"
            );
            Ok(ExitCode::from(0))
        }
        "sync" => run_agents_sync_command(args),
        other => Err(usage(format!(
            "unknown agents command: {other} (try: odc agents sync)"
        ))),
    }
}

fn run_agents_sync_command(args: &[String]) -> Result<ExitCode, CliError> {
    let mut path = None;
    for a in args.iter().skip(3) {
        if !a.starts_with('-') {
            path = Some(PathBuf::from(a));
        }
    }
    let root = resolve_root_path(
        path.unwrap_or_else(|| env::current_dir().unwrap_or_else(|_| PathBuf::from("."))),
    );
    let body = build_agents_md(&root);
    let agents_path = root.join("AGENTS.md");
    fs::write(&agents_path, &body).map_err(|e| failure(e.to_string()))?;
    println!("wrote {}", agents_path.display());

    let claude = root.join(".claude");
    let _ = fs::create_dir_all(&claude);
    let claude_rules = claude.join("opendocify-agents.md");
    fs::write(
        &claude_rules,
        "# OpenDocify agent notes\n\nSee [AGENTS.md](../AGENTS.md) generated by `odc agents sync`.\n\n\
         Use `odc ods context <id>` for ODS reading lists and `odc okf context <id>` for OKF.\n",
    )
    .map_err(|e| failure(e.to_string()))?;
    println!("wrote {}", claude_rules.display());

    let cursor = root.join(".cursor");
    let _ = fs::create_dir_all(&cursor);
    let cursor_rules = cursor.join("opendocify-agents.mdc");
    fs::write(
        &cursor_rules,
        "---\ndescription: OpenDocify multi-spec agent hints\nglobs:\nalwaysApply: false\n---\n\n\
         Prefer `odc ods` for codebase docs and `odc okf` for OKF knowledge bundles. \
         See root AGENTS.md.\n",
    )
    .map_err(|e| failure(e.to_string()))?;
    println!("wrote {}", cursor_rules.display());
    Ok(ExitCode::from(0))
}

fn build_agents_md(root: &Path) -> String {
    let mut md = String::from(
        "# AGENTS.md\n\n\
         Generated by `odc agents sync` (OpenDocify).\n\n\
         ## Specs in this repository\n\n",
    );
    if ods_core::ods_enabled(root) {
        md.push_str(
            "- **ODS** workspace (`ods:` root marker)\n\
             - Lint: `odc ods lint`\n\
             - Context: `odc ods context <id>`\n\
             - Audit: `odc ods audit --write-report`\n\n",
        );
    }
    if ods_core::okf_enabled(root) {
        md.push_str(
            "- **OKF v0.2** bundle (`okf_version` root marker)\n\
             - Lint: `odc okf lint`\n\
             - Context: `odc okf context <id>`\n\
             - Audit: `odc okf audit --write-report`\n\n",
        );
    }
    if !ods_core::ods_enabled(root) && !ods_core::okf_enabled(root) {
        md.push_str(
            "- No ODS/OKF root markers detected. Run `odc ods init` or `odc okf init`.\n\n",
        );
    }
    md.push_str(
        "## Rules for coding agents\n\n\
         1. Prefer `odc …` (auto-detect) or explicit `odc ods …` / `odc okf …` in CI.\n\
         2. ODS Markdown keys stay `ods:` / `odc:` — do not invent `odc-cli:`.\n\
         3. OKF concepts require `type:`; Attested Computation requires `runtime:`.\n\
         4. Do not execute OKF attesters/executors unless the user explicitly asks and tooling supports it.\n\
         5. After structural doc edits: `odc ods lint` or `odc okf lint` as appropriate.\n",
    );
    md
}
