fn write_or_clear_ods_error_report(
    root: &Path,
    diagnostics: &[Diagnostic],
    format: OutputFormat,
) -> Result<(), CliError> {
    let path = root.join("ods-error.md");
    if diagnostics.is_empty() {
        if path.is_file() {
            let _ = fs::remove_file(&path);
        }
        return Ok(());
    }
    // Only write the markdown report for human text mode (not pure JSON CI).
    if !matches!(format, OutputFormat::Text) {
        return Ok(());
    }
    let mut body = String::from(
        "---\nprofile: note\nstatus: draft\ndescription: ODS health report — auto-generated by ods lint / ods watch\n---\n\n# ODS errors\n\n",
    );
    body.push_str("Fix the items below, then re-run `ods lint` (or keep `ods watch` running).\n\n");
    for diagnostic in diagnostics {
        let severity = match diagnostic.severity {
            Severity::Error => "error",
            Severity::Warning => "warning",
        };
        let rel = diagnostic
            .path
            .strip_prefix(root)
            .unwrap_or(&diagnostic.path);
        body.push_str(&format!(
            "- **{severity}** `{}`: {}\n",
            rel.display(),
            diagnostic.message
        ));
    }
    fs::write(&path, body).map_err(|err| failure(err.to_string()))?;
    eprintln!("wrote {}", path.display());
    Ok(())
}
