fn dispatch_agents_command(args: &[String]) -> Result<ExitCode, CliError> {
    let sub = args.get(2).map(String::as_str).unwrap_or("help");
    match sub {
        "help" | "--help" | "-h" | "" => {
            println!(
                "ods agents <command>\n\n\
                 Agent instruction graph commands.\n\n\
                 Commands:\n\
                   sync [path]   Write/update AGENTS.md (+ optional .claude/.cursor snippets)\n\
                   help          Show this help\n"
            );
            Ok(ExitCode::from(0))
        }
        "sync" => run_agents_sync_command(args),
        other => Err(usage(format!(
            "unknown agents command: {other} (try: ods agents sync)"
        ))),
    }
}

fn run_agents_sync_command(args: &[String]) -> Result<ExitCode, CliError> {
    let mut path = None;
    for a in args.iter().skip(3) {
        if !a.starts_with('-') {
            path = Some(PathBuf::from(a));
        }
    }
    let root = resolve_root_path(
        path.unwrap_or_else(|| env::current_dir().unwrap_or_else(|_| PathBuf::from("."))),
    );
    let body = build_agents_md(&root);
    let agents_path = root.join("AGENTS.md");
    fs::write(&agents_path, &body).map_err(|e| failure(e.to_string()))?;
    println!("wrote {}", agents_path.display());

    let claude = root.join(".claude");
    let _ = fs::create_dir_all(&claude);
    let claude_rules = claude.join("opendocify-agents.md");
    fs::write(
        &claude_rules,
        "# Open Document Spec agent notes\n\nSee [AGENTS.md](../AGENTS.md) generated by `ods agents sync`.\n\n\
         Use `ods context <id>` for ODS reading lists and `ods context --okf <id>` for OKF.\n",
    )
    .map_err(|e| failure(e.to_string()))?;
    println!("wrote {}", claude_rules.display());

    let cursor = root.join(".cursor");
    let _ = fs::create_dir_all(&cursor);
    let cursor_rules = cursor.join("opendocify-agents.mdc");
    fs::write(
        &cursor_rules,
        "---\ndescription: Open Document Spec multi-spec agent hints\nglobs:\nalwaysApply: false\n---\n\n\
         Prefer bare `ods` for codebase docs and `ods … --okf` for OKF knowledge bundles. \
         See root AGENTS.md.\n",
    )
    .map_err(|e| failure(e.to_string()))?;
    println!("wrote {}", cursor_rules.display());
    Ok(ExitCode::from(0))
}

fn build_agents_md(root: &Path) -> String {
    let mut md = String::from(
        "# AGENTS.md\n\n\
         Generated by `ods agents sync` (Open Document Spec).\n\n\
         ## Specs in this repository\n\n",
    );
    if ods_core::ods_enabled(root) {
        md.push_str(
            "- **ODS** workspace (`ods:` root marker)\n\
             - Lint: `ods lint`\n\
             - Context: `ods context <id>`\n\
             - Audit: `ods audit --write-report`\n\n",
        );
    }
    if ods_core::okf_enabled(root) {
        md.push_str(
            "- **OKF v0.2** bundle (`okf_version` root marker)\n\
             - Lint: `ods lint --okf`\n\
             - Context: `ods context --okf <id>`\n\
             - Audit: `ods audit --okf --write-report`\n\n",
        );
    }
    if !ods_core::ods_enabled(root) && !ods_core::okf_enabled(root) {
        md.push_str(
            "- No ODS/OKF root markers detected. Run `ods init` or `ods init --okf`.\n\n",
        );
    }
    md.push_str(
        "## Rules for coding agents\n\n\
         1. Bare `ods <cmd>` is ODS-native (no `--ods` flag). Extra specs: `--okf`, `--skills` only — never namespaces.\n\
         2. ODS Markdown keys use nested `ods:` engine map and root `ods:` version marker — do not invent `ods-cli:` or `odc:`.\n\
         3. OKF concepts require `type:`; Attested Computation requires `runtime:` (use `ods lint --okf`).\n\
         4. Do not execute OKF attesters/executors unless the user explicitly asks and tooling supports it.\n\
         5. After structural doc edits: `ods lint` (and `ods lint --okf` / `ods lint --skills` when those trees changed).\n",
    );
    md
}
